spring.application.name=study-apir

# alterar porta do servidor
server.port=9000

# swagger na raiz da aplicacao
springdoc.swagger-ui.path=/

api.version=v1

#configuracao do banco
spring.datasource.url=jdbc:mysql://localhost:3306/api?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root_pwd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect